mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:/mappers/**.xml
  type-aliases-package: com.example.demo.Model

mapper:
  mappers: com.example.demo.util.MyMapper
  not-empty: true
  identity: MYSQL
spring:
  elasticsearch:
    rest:
      uris: 47.100.4.109:9200
      username: root
      password: 123456
  datasource:
    url: jdbc:mysql://47.100.4.109:3306/suiji?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: Password123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  main:
    allow-bean-definition-overriding: true
rocketmq:
  nameserver: 47.100.4.109:9876
  producer:
    group: producer-group
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 60 # 验证码超期时间
  host: localhost # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  timeout: 3000ms # 连接超时时间（毫秒）